/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Conexion_Personal;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class Panel_Cargos extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Cargos
     */
    public Panel_Cargos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCargo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombreC = new javax.swing.JTextField();
        RegistrarC = new javax.swing.JButton();
        BorrarC = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("idCargo");

        jLabel2.setText("NombreCargo");

        RegistrarC.setText("Registrar");
        RegistrarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarCActionPerformed(evt);
            }
        });

        BorrarC.setText("Borrar");
        BorrarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegistrarC)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BorrarC))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrarC)
                    .addComponent(BorrarC))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarCActionPerformed
        // TODO add your handling code here:
        
        
        
              Conexion_P conexion = new Conexion_P();  // Crear una instancia de la clase ConexionBD
        Connection con = conexion.establecerconexion();  // Establecer la conexión

        if (con != null) {  // Verificar si la conexión fue exitosa
            try {
                // Preparar la consulta SQL
                PreparedStatement pps = con.prepareStatement("INSERT INTO cargos (idCargo,NombreCargo) VALUES (?, ?)");

                // Establecer los valores de los parámetros
                pps.setString(1, txtCargo.getText());
                pps.setString(2, txtNombreC.getText());
 

                // Ejecutar la consulta
                pps.executeUpdate();

                // Mostrar mensaje de éxito
                JOptionPane.showMessageDialog(null, "Datos guardados");

                // Cerrar la conexión
                con.close();

            } catch (SQLException ex) {
                Logger.getLogger(Panel_Personal.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Error al guardar los datos: " + ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Conexión a la base de datos fallida.");
        }
    }//GEN-LAST:event_RegistrarCActionPerformed

    private void BorrarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarCActionPerformed
        // TODO add your handling code here:
         Conexion_P conexion = new Conexion_P();  
    Connection con = conexion.establecerconexion();  // Establecer la conexión

    if (con != null) {  // Verificar si la conexión fue exitosa
        try {
            // Preparar la consulta SQL para eliminar
            PreparedStatement pps = con.prepareStatement("DELETE FROM usuarios WHERE Codigo = ?");
            
            // Establecer el valor del parámetro (Código del usuario)
            pps.setString(1, txtCargo.getText());
            
            // Ejecutar la consulta
            int resultado = pps.executeUpdate();
            
            if (resultado > 0) {
                // Mostrar mensaje de éxito si se eliminó el registro
                JOptionPane.showMessageDialog(null, "Registro eliminado exitosamente.");
            } else {
                // Mostrar mensaje si no se encontró un registro con ese Código
                JOptionPane.showMessageDialog(null, "No se encontró un registro con ese código.");
            }
            
            // Cerrar la conexión
            con.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(Panel_Personal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Error al eliminar los datos: " + ex.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(null, "Conexión a la base de datos fallida.");
    }
        
    
    
        
    }//GEN-LAST:event_BorrarCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BorrarC;
    private javax.swing.JButton RegistrarC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtNombreC;
    // End of variables declaration//GEN-END:variables
}
